#!/bin/python3
import socket
import struct
import sys
from binascii import hexlify


if len(sys.argv) < 2:
    print("wrong usage !!!")
    exit(1)
sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
#sock.bind("/tmp/dwmrcvsocket991199")



#id =   int(input("id: "))
#pid =  int(input("pid: "))
#mon =  int(input("mon: "))
#tag =  (1 << int(input("tag: ")))

id = int(sys.argv[1])
pid = int(sys.argv[2])
mon = int(sys.argv[3])
tag = (1 << (int(sys.argv[4])-1)) if int(sys.argv[4]) else 0


pk = struct.pack("iiii",id,pid,mon,tag)

server_address = "/tmp/dwmsocket"
#print("sending ", sys.argv[1],"to", server_address)




try:
    sock.connect(server_address)
    sock.send(pk)
    print(sock.recv(1024).decode())
except Exception as e:
    print(e)
